### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by some-mthfka** [attila-lendvai/hu.dwim.sdl#1]
Hi! The .asd file states that the license is "BSD or Bugroff", but with BSD having multiple variations and all, it would be really nice to actually place a license file explicitly in the repo (I think most licenses require this), so that there's no ambiguity. Could you please add it?

I am working on a fork of this project where I lispyfy the names, I am going to publish it once I have tested it a bit, so I think a license would be good.

**Comment by attila-lendvai** [comment]
i reject the very notion that it's ever justified to initiate the use of force against someone for using published information... hence the buggroff part. but anyway, i added a BSD file.

looking forward to what changes you have in mind! AFAIK, this project is only used by https://github.com/projectured/projectured which is also "our" code, and rather dormant for years.

**Comment by some-mthfka** [comment]
Cool, thanks!
