### ISSUE TITLE
naming and stuff

### ISSUE THREAD

**Issue by some-mthfka** [attila-lendvai/hu.dwim.sdl#2]
So, I have finished reworking the naming stuff along with the error-checking/bool conversions.

https://github.com/some-mthfka/hu.dwim.sdl (note that it relies on this pr: https://github.com/cffi/cffi/pull/180)

If you are ok with the changes and think it would be a good idea, I can meld the `fork` section of the readme with the rest of it and make a pull request. Though I think it wouldn't hurt to do a little rebranding and create a new system which has `sdl2` explicitly in the name (when I first found this on quicklisp, I thought this was for SDL 1). But I don't mind either way.

**Comment by attila-lendvai** [comment]
re project naming: i didn't really consider the fact that `libsdl2.so` is not API compatible with `libsdl.so`, nor that SDL3 will not arrive in the few years that have passed.

do you think it would make sense and worth the trouble to rename the repo and the project to `hu.dwim.sdl2`? what if when SDL3 arrives?

**Comment by attila-lendvai** [comment]
> The generated names are lispy now.

i assume that it's not an addition, but a change, right? i'm not happy about that. i deliberately decided to keep the names as-is to avoid the mental load when reading the SDL docs, and/or when looking at some SDL examples. my reasoning was that if something from SDL is used often in the code, then it's most probably going to end up getting hidden behind a higher level lispy abstraction that can have its own lispy name.

i'm not against providing lispy names in some new package, but i don't think it's a good idea **not** to have the original names, and in general not to have a very "low impedance mismatch" version of the C API available on the lisp side.

**Comment by attila-lendvai** [comment]
what was the motivation for cutting the C namespace into separate lisp packages? my gut reaction is that it's probably not worth the extra complexity. the SDL subsystems share the same C namespace, there shouldn't be any clashes.

**Comment by attila-lendvai** [comment]
i'll look into regenerating the c2ffi bindings. ping me if there's no word from me.

**Comment by some-mthfka** [comment]
> do you think it would make sense and worth the trouble to rename the repo and the project to hu.dwim.sdl2? what if when SDL3 arrives?

No, nevermind that. I was under the impressions that SDL1.2 was actually competing with SDL2 because on arch linux there's still 1.2 distribution going https://archlinux.org/packages/community/x86_64/sdl/, but that's probably for the purpose of supporting some applications that didn't migrate.

> i'm not against providing lispy names in some new package, but i don't think it's a good idea not to have the original names, and in general not to have a very "low impedance mismatch" version of the C API available on the lisp side.

I agree with you on that. But I don't know how to generate multiple version of a function with cffi.

> what was the motivation for cutting the C namespace into separate lisp packages? my gut reaction is that it's probably not worth the extra complexity. the SDL subsystems share the same C namespace, there shouldn't be any clashes.

I think it's nicer. I mean, if you have everything in one package, the user probably nicknames `hu.dwim.sdl/ffi` something like `sdl` in their code. So you end up with `sdl:sdl-init` instead of the simple `sdl:init` or `ttf:init`. Also, it's always clear in the code where a certain function is coming from, fwiw.

> i'll look into regenerating the c2ffi bindings. ping me if there's no word from me.

Alright!

**Comment by attila-lendvai** [comment]
FWIW, the way i originally envisioned it is that there's a single lisp-side package holding a one-to-one mirror of the vanilla C namespace, and then there would be one (or more?) additional lisp packages (currently `hu.dwim.sdl`) that would hold the lispy names, and import/reexport part of the C API under lispy names, alongside the added, higher level lisp constructs.

**Comment by some-mthfka** [comment]
And are the generated functions doing any error checking? If yes, you would still have to insert the original, unempeded function right by for the Pure C Experience TM (prepending with % still sounds like a good plan).

**Comment by some-mthfka** [comment]
Probably, the really right solution _if_ you want to accomplish seperation would be to make cffi generate multiple files, each having its own package (and with it's own cffi options, of course). Like `%core` for C equivalents, `core` for functions with conversions/checks, and then, if your (generated) utilities don't have a naming scheme making them unique (mine don't), maybe even `core+` or `core*`. All of this could be taken pretty far. Hell, if you wanted automatically wrapped gc functions, that could be `core-gc`. And what's the point anyway? Avoid the improbable name clashes? Noble, but the API ends up confusing for the user and adds code right on top of maintenance efforts. 

A decent way to go, as I see it now, is to indeed generate multiple files when necessary or, well, multiple versions of a function in the same file if cffi allowed it, (for me, that's just for the unempeded versions for now, but I imagine gc would need it too if somebody needed it), whatever is easier, keeping everything in one package, while choosing a naming scheme that minimizes the possibilities of clashes, all while being sane and usable. And if a name clash occurs, rename the newly introduced function to keep the compatibility.

**Comment by attila-lendvai** [comment]
re spec file regeneration:

i pushed a script file that can be used to regenerate the spec files -- except that i cannot make c2ffi work, due to some errors related to llvm/clang intrinsics.

see https://github.com/rpav/c2ffi/pull/89 for details.

**Comment by attila-lendvai** [comment]
@some-mthfka i have managed to regenerate the spec files, and projectured works as before.

open a new issue if you find anything that you're missing.

**Comment by some-mthfka** [comment]
@attila-lendvai Awesome, thanks! Just for the sake of it, I tried your script, but it kept fetching CFFI from quicklisp, even though I had the new cffi in local-projects. Guess that won't be a problem once quicklisp has the latest version, though. 

Interestingly enough, I just tried another machine with Arch Linux, and cffi/c2ffi generated the specs for me just fine! No clue why it didn't work on my main computer with pretty much the same setup (though different hardware). Oh well.

BTW I fixed the pr at https://github.com/cffi/cffi/pull/180 as requested, could you please take a look at it again?

**Comment by attila-lendvai** [comment]
i'll get to it, slowly. that codebase much more needs a cleanup than patching... so i'm looking if it's possible to make that PR unnecessary but changing other stuff.

if you want to load your local cffi, then you need to move its loading from `quickload` into a simple `asdf:load-system`, and comment out the `export CL_SOURCE_REGISTRY` part on the top.

**Comment by some-mthfka** [comment]
OK! Speaking of C2FFI and hacks, I also had to use `output/code` from within `ffi-type-transformer` in order to place necessary type declarations and expand methods before function definitions (based on the function name and its return type). While it's overall innocuous (imo), `output/code` is unexported, and it's not very obvious and transparent...

**Comment by attila-lendvai** [comment]
that's probably fine, as long as:
- there aren't many users
- they do coordinate
- or breakage is loud and clear.

too much energy put into what's exported, and into a proper API design, is only worth it when a lot of people need to coordinate. that's hardly the case with cffi/c2ffi. i'm not sure anyone else have ever used it before you.

**Comment by some-mthfka** [comment]
Alright, gotcha!

**Comment by attila-lendvai** [comment]
@some-mthfka after all that's discussed above, are you still unsatisfied with the current situation? if so, can you please write a few words on the bird's eye view of what new state you would find satisfactory?

**Comment by some-mthfka** [comment]
@attila-lendvai for me, everything looks good except for the linked PR. If it's not accepted, I would have to resort to some kludge, like doing the insertion on the first call of ffi-type-transformer or the name converter or something like that.
I understand that maybe the prologue feature doesn't promote the way in which c2ffi was envisioned to be used initially, but, there being the epilogue code as is, it only seems to naturally extend what's already in place, without really corrupting anything. So, all in all, I don't get the reluctance either.

**Comment by attila-lendvai** [comment]
ok, i'll close this then, but look into merging that other cffi/c2ffi PR.
